#importing the library

reading the csv file

In [25]:
import pandas as pd

df = pd.read_csv("archive/Combined_dataset.csv")

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

tells us (no. of row ,no. of colmns)

In [26]:
df.shape

(1000, 24)

gives last 5 rows

In [27]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

gives all the column names

In [28]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

shows all the data types of columns

In [29]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

TASK -3 HANDLE MISSING VALUES

identifies the missing values

In [31]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

fill the missing values

In [32]:
df["discount"] = df["discount"].fillna(df["discount"].mean())

verfying if the missing values are filled with mean or not

In [33]:
df["discount"].isnull().sum()

np.int64(0)

for text columns fill the missing values with not available

In [34]:
df["what_customers_said"] = df["what_customers_said"].fillna("Not Available")
df["seller_name"] = df["seller_name"].fillna("Not Available")
df["videos"] = df["videos"].fillna("Not Available")
df["seller_information"] = df["seller_information"].fillna("Not Available")
df["variations"] = df["variations"].fillna("Not Available")

hence verified all the missing values are filled and now we dont have any missing value

In [35]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

we could also drop the missing values instead of filling them

In [36]:
df.dropna()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""pi-13698258""]",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]",Not Available,Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Not Available,Tru███m R███il,"[{""size"":""Onesize""}]",Not Available,Sho███o. ███-10█████████enu███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Not Available,Not Available,"[{""size"":""Medium""}]",Not Available,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

TASK -4 SELECT COL/ FILTER ROWS

select cols -> shows only the cols we need to see at the perticular moment

In [37]:
df[["title", "category", "rating", "final_price"]]

              title   category  rating   final_price
0       Lino Perros  backpacks     3.8   "₹3,995.00"
1    Tommy Hilfiger  backpacks     4.5   "₹2,899.00"
2             Lavie  backpacks     4.4   "₹2,999.00"
3            F Gear  backpacks     4.4   "₹1,675.00"
4         MYTRIDENT  bath-robe     4.7   "₹2,899.00"
..              ...        ...     ...           ...
995           KREDO    watches     3.5  "₹11,890.00"
996           GUESS    watches     5.0   "₹8,900.00"
997        GIORDANO    watches     2.8   "₹7,950.00"
998        Fastrack    watches     4.3   "₹2,636.00"
999         BOLDFIT  yoga-mats     3.8     "₹699.00"

[1000 rows x 4 columns]

filter rows -> shows only the rows which satisfies the given condition

In [38]:
df[df["rating"] > 4.5]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",Not Available,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.000000,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",Not Available,SAI███USE███OT █████████ NA███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,53.503982,"""₹345.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",Not Available,VI/███ AB███ ST█████████ODE███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.000000,"""₹815.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",Not Available,Sho███58-███Sec█████████ain███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.000000,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",Not Available,Bod███ove███par█████████ No███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
968,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.000000,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",Not Available,621███ 6n███ kh█████████zia███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.000000,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",Not Available,"Fla███o. ███, 6█████████y C███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.000000,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.000000,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

TASK -5 REMOVE DUPLICATES

FIRST WE COUNT ALL DUPLICATE ROWS

In [39]:
df.duplicated().sum()

np.int64(0)

here since we dont have any duplicate rows but if we had so we can remove them

In [40]:
df = df.drop_duplicates()

lets verify

In [41]:
df.duplicated().sum()

np.int64(0)

TASK -6 CREATING A DREIVED COLUMN

checking the data type for making the derived column

In [42]:
df[["initial_price", "discount"]].head()

   initial_price  discount
0           3995      58.0
1           2899      35.0
2           2999      65.0
3           1675      52.0
4           2899      17.0

now we will make a column which will give us a discount amout which is derived from initial price and discount

In [43]:
df["discount_amount"] = df["initial_price"] * df["discount"] / 100

verifying the derived column

In [44]:
df[["initial_price", "discount", "discount_amount"]].head()

   initial_price  discount  discount_amount
0           3995      58.0          2317.10
1           2899      35.0          1014.65
2           2999      65.0          1949.35
3           1675      52.0           871.00
4           2899      17.0           492.83

TASK -7 SAVEING THE CLEAN DATASET

here we converted are data frame into csv file and named it and also removed the index column

In [45]:
df.to_csv("week_1_cleaned_dataset.csv", index=False)

In [46]:
import os

os.listdir()

['.DS_Store',
 'archive',
 'week_1_cleaned_dataset.csv',
 'venv',
 'week1_assignment.ipynb']

 Brief Summary

- Loaded the shopping dataset using Pandas.
- Explored the dataset using head(), tail(), shape, columns, dtypes, and info().
- Identified missing values using isnull().sum().
- Filled missing numerical values in the discount column using the mean value.
- Filled missing categorical values with "Not Available".
- Selected important columns and filtered products based on rating.
- Checked for and removed duplicate records.
- Created a derived column named discount_amount.
- Saved the cleaned dataset as cleaned_dataset.csv.