In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("ecommerce.db")
cursor = conn.cursor()

print("Database created successfully")

Database created successfully

# Create Tables

In [2]:
cursor.executescript("""
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    city TEXT,
    state TEXT,
    join_date DATE,
    is_premium BOOLEAN
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT,
    brand TEXT,
    unit_price REAL CHECK(unit_price > 0),
    stock_qty INTEGER
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date DATE,
    status TEXT,
    total_amount REAL,
    FOREIGN KEY(customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    item_id INTEGER PRIMARY KEY,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    unit_price REAL,
    discount_pct REAL,
    FOREIGN KEY(order_id)
    REFERENCES orders(order_id),
    FOREIGN KEY(product_id)
    REFERENCES products(product_id)
);
""")

conn.commit()

### Insert Customers

In [3]:
cursor.executescript("""
INSERT INTO customers VALUES
(101,'Aarav','Sharma','aarav.s@email.com','Mumbai','Maharashtra','2024-01-15',1),
(102,'Priya','Patel','priya.p@email.com','Ahmedabad','Gujarat','2024-02-20',0),
(103,'Rohan','Gupta','rohan.g@email.com','Delhi','Delhi','2024-03-10',1),
(104,'Sneha','Reddy','sneha.r@email.com','Hyderabad','Telangana','2024-04-05',0),
(105,'Vikram','Singh','vikram.s@email.com','Jaipur','Rajasthan','2024-05-12',1),
(106,'Ananya','Iyer','ananya.i@email.com','Chennai','Tamil Nadu','2024-06-18',0),
(107,'Karan','Mehta','karan.m@email.com','Pune','Maharashtra','2024-07-22',1),
(108,'Divya','Nair','divya.n@email.com','Kochi','Kerala','2024-08-30',0);
""")

conn.commit()

###  Insert Products

In [4]:
cursor.executescript("""
INSERT INTO products VALUES
(201,'Wireless Earbuds','Electronics','BoAt',1499,250),
(202,'Cotton T-Shirt','Clothing',"Levi's",799,500),
(203,'Smart Watch','Electronics','Noise',2999,150),
(204,'Running Shoes','Clothing','Nike',4599,120),
(205,'Bluetooth Speaker','Electronics','JBL',3499,200),
(206,'Bedsheet Set','Home','Spaces',1299,300),
(207,'Laptop Stand','Electronics','AmazonBasics',899,180),
(208,'Cushion Covers (Set)','Home','HomeCenter',599,400);
""")

conn.commit()

### Insert Orders

In [5]:
cursor.executescript("""
INSERT INTO orders VALUES
(1001,101,'2024-08-01','Delivered',4498),
(1002,102,'2024-08-03','Delivered',799),
(1003,103,'2024-08-05','Shipped',7498),
(1004,101,'2024-08-10','Delivered',3499),
(1005,104,'2024-08-12','Cancelled',2999),
(1006,105,'2024-08-15','Delivered',5898),
(1007,106,'2024-08-18','Pending',1299),
(1008,103,'2024-08-20','Delivered',899),
(1009,107,'2024-08-25','Shipped',6098),
(1010,108,'2024-08-28','Delivered',1598);
""")

conn.commit()

### Insert Order Items

In [18]:
cursor.execute("""
CREATE TABLE order_items (
    item_id INTEGER PRIMARY KEY,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    unit_price REAL,
    discount_pct REAL
)
""")

conn.commit()

print("order_items table created")

order_items table created

In [19]:
cursor.executescript("""
INSERT INTO order_items VALUES
(5001, 1001, 201, 2, 1499.00, 0), 
(5002, 1001, 207, 1, 899.00,  10), 
(5003, 1002, 202, 1, 799.00,  0), 
(5004, 1003, 203, 1, 2999.00, 0), 
(5005, 1003, 204, 1, 4599.00, 5), 
(5006, 1004, 205, 1, 3499.00, 0), 
(5007, 1005, 203, 1, 2999.00, 0), 
(5008, 1006, 201, 1, 1499.00, 10), 
(5009, 1006, 204, 1, 4599.00, 5), 
(5010, 1007, 206, 1, 1299.00, 0), 
(5011, 1008, 207, 1, 899.00,  0), 
(5012, 1009, 205, 1, 3499.00, 0), 
(5013, 1009, 208, 2, 599.00,  15), 
(5014, 1010, 206, 1, 1299.00, 0), 
(5015, 1010, 208, 1, 599.00,  0); 
""")

conn.commit()

print("Order items inserted successfully")

Order items inserted successfully

# Section A Solutions

## Q1. Display all columns and rows from the customers table

This query retrieves every column and every row present in the customers table.

In [8]:
pd.read_sql_query("""
SELECT *
FROM customers
""", conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

## Q2. Retrieve first_name, last_name and city of all customers

Only the required columns are selected instead of displaying the entire table.

In [9]:
pd.read_sql_query("""
SELECT first_name,
        last_name,
        city
FROM customers
""", conn)

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

## Q3. List all unique product categories

DISTINCT removes duplicate values and returns only unique categories.

In [13]:
pd.read_sql_query("""
SELECT DISTINCT category
FROM products
""", conn)

      category
0  Electronics
1     Clothing
2         Home

## Q4. Primary Keys in the Database

Primary Keys:

customers      → customer_id
products       → product_id
orders         → order_id
order_items    → item_id

Why Primary Keys are important:

1. Every record must be uniquely identifiable.
2. Primary Keys cannot contain NULL values.
3. Duplicate values are not allowed.
4. They maintain entity integrity and support relationships between tables.

## Q5. Constraints on email column

The email column should have:

- UNIQUE constraint
- NOT NULL constraint

Example:

email VARCHAR(100) UNIQUE NOT NULL

## Q6. Attempt to insert a product with a negative price

The products table contains a CHECK constraint:

CHECK(unit_price > 0)

This prevents invalid prices from being inserted.

In [20]:
try:
    cursor.execute("""
    INSERT INTO products
    VALUES (
        999,
        'Invalid Product',
        'Electronics',
        'TestBrand',
        -50,
        10
    )
    """)

    conn.commit()

except Exception as e:
    print(e)

CHECK constraint failed: unit_price > 0

# Section B — Filtering & Optimization (WHERE, Indexes)

## Q7. Retrieve all orders with status = 'Delivered'

In [21]:
pd.read_sql_query("""
SELECT *
FROM orders
WHERE status = 'Delivered'
""", conn)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1004          101  2024-08-10  Delivered        3499.0
3      1006          105  2024-08-15  Delivered        5898.0
4      1008          103  2024-08-20  Delivered         899.0
5      1010          108  2024-08-28  Delivered        1598.0

This query filters the orders table and returns only the orders whose status is 'Delivered'.

## Q8. Electronics products with unit_price greater than ₹2000

In [22]:
pd.read_sql_query("""
SELECT *
FROM products
WHERE category = 'Electronics'
AND unit_price > 2000
""", conn)

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise      2999.0        150
1         205  Bluetooth Speaker  Electronics    JBL      3499.0        200

This query returns products that belong to the Electronics category and have a unit price above ₹2000.

## Q9. Customers who joined in 2024 and belong to Maharashtra

In [23]:
pd.read_sql_query("""
SELECT *
FROM customers
WHERE state = 'Maharashtra'
AND join_date BETWEEN '2024-01-01' AND '2024-12-31'
""", conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

This query retrieves customers from Maharashtra who joined during the year 2024.

## Q10. Orders placed between 2024-08-10 and 2024-08-25 that are not cancelled

In [24]:
pd.read_sql_query("""
SELECT *
FROM orders
WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
AND status <> 'Cancelled'
""", conn)

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered        3499.0
1      1006          105  2024-08-15  Delivered        5898.0
2      1007          106  2024-08-18    Pending        1299.0
3      1008          103  2024-08-20  Delivered         899.0
4      1009          107  2024-08-25    Shipped        6098.0

This query returns orders placed within the specified date range excluding cancelled orders.

## Q11. What does idx_orders_date do?

The index idx_orders_date is created on the order_date column.

Purpose:
- It speeds up searching and filtering operations on order_date.
- Instead of scanning every row in the table, SQLite can directly locate matching records through the index.
- This significantly improves performance on large datasets.

Example query that benefits from this index:

In [25]:
pd.read_sql_query("""
SELECT *
FROM orders
WHERE order_date BETWEEN '2024-08-01' AND '2024-08-31'
""", conn)

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1003          103  2024-08-05    Shipped        7498.0
3      1004          101  2024-08-10  Delivered        3499.0
4      1005          104  2024-08-12  Cancelled        2999.0
5      1006          105  2024-08-15  Delivered        5898.0
6      1007          106  2024-08-18    Pending        1299.0
7      1008          103  2024-08-20  Delivered         899.0
8      1009          107  2024-08-25    Shipped        6098.0
9      1010          108  2024-08-28  Delivered        1598.0

Without an index, SQLite performs a full table scan.
With the index, SQLite can quickly locate matching dates.

## Q12. Would the index on join_date be used?

Query: SELECT *
FROM customers
WHERE YEAR(join_date) = 2024;

No.

Reason:
Applying a function (YEAR) to the indexed column forces the database to evaluate every row, preventing efficient index usage.

This makes the query non-SARGable.

Index-friendly version:

In [26]:
pd.read_sql_query("""
SELECT *
FROM customers
WHERE join_date >= '2024-01-01'
AND join_date < '2025-01-01'
""", conn)

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

This version allows SQLite to use the index on join_date efficiently because the column is compared directly without applying any function.

# Section C — Aggregation (GROUP BY, SUM, COUNT, AVG, MIN, MAX)

## Q13. Count the total number of orders

In [27]:
pd.read_sql_query("""
SELECT COUNT(*) AS total_orders
FROM orders
""", conn)

   total_orders
0            10

COUNT(*) counts all rows present in the orders table.

## Q14. Total revenue from Delivered orders

In [28]:
pd.read_sql_query("""
SELECT SUM(total_amount) AS total_revenue
FROM orders
WHERE status = 'Delivered'
""", conn)

   total_revenue
0        17191.0

SUM(total_amount) calculates the total revenue generated from all delivered orders.

## Q15. Average unit price of products in each category

In [29]:
pd.read_sql_query("""
SELECT category,
       ROUND(AVG(unit_price),2) AS average_price
FROM products
GROUP BY category
""", conn)

      category  average_price
0     Clothing         2699.0
1  Electronics         2224.0
2         Home          949.0

AVG(unit_price) calculates the average product price for each category.

## Q16. Count of orders and total revenue by status

In [30]:
pd.read_sql_query("""
SELECT status,
       COUNT(*) AS total_orders,
       SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status
ORDER BY total_revenue DESC
""", conn)

      status  total_orders  total_revenue
0  Delivered             6        17191.0
1    Shipped             2        13596.0
2  Cancelled             1         2999.0
3    Pending             1         1299.0

This query groups orders by status, counts the orders in each group, calculates total revenue, and sorts results by revenue in descending order.

## Q17. Most expensive and cheapest product in each category

In [31]:
pd.read_sql_query("""
SELECT category,
       MAX(unit_price) AS most_expensive,
       MIN(unit_price) AS cheapest
FROM products
GROUP BY category
""", conn)

      category  most_expensive  cheapest
0     Clothing          4599.0     799.0
1  Electronics          3499.0     899.0
2         Home          1299.0     599.0

MAX(unit_price) returns the highest priced product and MIN(unit_price) returns the lowest priced product in each category.

## Q18. Categories with average unit price greater than ₹2000

In [32]:
pd.read_sql_query("""
SELECT category,
       ROUND(AVG(unit_price),2) AS average_price
FROM products
GROUP BY category
HAVING AVG(unit_price) > 2000
""", conn)

      category  average_price
0     Clothing         2699.0
1  Electronics         2224.0

HAVING filters grouped results. This query returns only categories whose average unit price exceeds ₹2000.

## Q19. Display each order with customer details using INNER JOIN

In [33]:
pd.read_sql_query("""
SELECT
    o.order_id,
    o.order_date,
    c.first_name,
    c.last_name,
    o.total_amount
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id
ORDER BY o.order_id
""", conn)

   order_id  order_date first_name last_name  total_amount
0      1001  2024-08-01      Aarav    Sharma        4498.0
1      1002  2024-08-03      Priya     Patel         799.0
2      1003  2024-08-05      Rohan     Gupta        7498.0
3      1004  2024-08-10      Aarav    Sharma        3499.0
4      1005  2024-08-12      Sneha     Reddy        2999.0
5      1006  2024-08-15     Vikram     Singh        5898.0
6      1007  2024-08-18     Ananya      Iyer        1299.0
7      1008  2024-08-20      Rohan     Gupta         899.0
8      1009  2024-08-25      Karan     Mehta        6098.0
9      1010  2024-08-28      Divya      Nair        1598.0

INNER JOIN returns only matching records from both tables.
Each order is matched with the customer who placed it.

## Q20. Display all customers and their orders using LEFT JOIN

In [34]:
pd.read_sql_query("""
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.status
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
ORDER BY c.customer_id
""", conn)

   customer_id first_name last_name  order_id  order_date     status
0          101      Aarav    Sharma      1001  2024-08-01  Delivered
1          101      Aarav    Sharma      1004  2024-08-10  Delivered
2          102      Priya     Patel      1002  2024-08-03  Delivered
3          103      Rohan     Gupta      1003  2024-08-05    Shipped
4          103      Rohan     Gupta      1008  2024-08-20  Delivered
5          104      Sneha     Reddy      1005  2024-08-12  Cancelled
6          105     Vikram     Singh      1006  2024-08-15  Delivered
7          106     Ananya      Iyer      1007  2024-08-18    Pending
8          107      Karan     Mehta      1009  2024-08-25    Shipped
9          108      Divya      Nair      1010  2024-08-28  Delivered

LEFT JOIN returns all customers.
If a customer has no order, order-related columns appear as NULL.

## Q21. Display product details for every order item

In [35]:
pd.read_sql_query("""
SELECT
    o.order_id,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_pct
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON oi.product_id = p.product_id
ORDER BY o.order_id
""", conn)

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2      1499.0           0.0
1       1001          Laptop Stand         1       899.0          10.0
2       1002        Cotton T-Shirt         1       799.0           0.0
3       1003           Smart Watch         1      2999.0           0.0
4       1003         Running Shoes         1      4599.0           5.0
5       1004     Bluetooth Speaker         1      3499.0           0.0
6       1005           Smart Watch         1      2999.0           0.0
7       1006      Wireless Earbuds         1      1499.0          10.0
8       1006         Running Shoes         1      4599.0           5.0
9       1007          Bedsheet Set         1      1299.0           0.0
10      1008          Laptop Stand         1       899.0           0.0
11      1009     Bluetooth Speaker         1      3499.0           0.0
12      1009  Cushion Covers (Set)         2       599.0          15.0
13      1010          Bedsheet Set         1      1299.0           0.0
14      1010  Cushion Covers (Set)         1       599.0           0.0

This query joins three tables:
Orders → Order_Items → Products

It shows which products were purchased in each order.

## Q22. Difference between LEFT JOIN and RIGHT JOIN

LEFT JOIN:
Returns all records from the left table and matching records from the right table.

Example:
customers LEFT JOIN orders

Result:
All customers are displayed.
Customers without orders show NULL values for order columns.

RIGHT JOIN:
Returns all records from the right table and matching records from the left table.

Example:
customers RIGHT JOIN orders

Result:
All orders are displayed.
Orders without matching customers show NULL values for customer columns.

FULL OUTER JOIN:
Returns all matching and non-matching rows from both tables.

Use Case:
When you want every customer and every order, even if no matching record exists.

Note:
SQLite does not support FULL OUTER JOIN directly.

## Q23. Foreign Key Relationships

In [36]:
pd.read_sql_query("""
PRAGMA foreign_key_list(orders)
""", conn)
pd.read_sql_query("""
PRAGMA foreign_key_list(order_items)
""", conn)

Empty DataFrame
Columns: [id, seq, table, from, to, on_update, on_delete, match]
Index: []

Foreign Keys in this schema:

1. orders.customer_id
   → customers.customer_id

2. order_items.order_id
   → orders.order_id

3. order_items.product_id
   → products.product_id

Purpose:
Foreign Keys maintain referential integrity between tables.

In [37]:
try:
    cursor.execute("""
    INSERT INTO orders
    VALUES
    (2000, 999, '2024-09-01', 'Delivered', 1000)
    """)
    conn.commit()

except Exception as e:
    print(e)

The insert will fail because customer_id = 999 does not exist in the customers table.

SQLite Error:
FOREIGN KEY constraint failed

The foreign key constraint prevents orphan records and maintains data consistency.

In [38]:
pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

          name
0    customers
1     products
2       orders
3  order_items

# Section E — Advanced Concepts (CASE, ACID, Transactions)

## Q24. Classify products into price tiers using CASE

In [39]:
pd.read_sql_query("""
SELECT
    product_name,
    unit_price,
    CASE
        WHEN unit_price < 1000 THEN 'Budget'
        WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
        ELSE 'Premium'
    END AS price_tier
FROM products
ORDER BY unit_price
""", conn)

           product_name  unit_price price_tier
0  Cushion Covers (Set)       599.0     Budget
1        Cotton T-Shirt       799.0     Budget
2          Laptop Stand       899.0     Budget
3          Bedsheet Set      1299.0  Mid-Range
4      Wireless Earbuds      1499.0  Mid-Range
5           Smart Watch      2999.0  Mid-Range
6     Bluetooth Speaker      3499.0    Premium
7         Running Shoes      4599.0    Premium

Products are classified into:

- Budget → unit_price < 1000
- Mid-Range → unit_price BETWEEN 1000 AND 3000
- Premium → unit_price > 3000

## Q25. Count Delivered vs Not Delivered Orders

In [40]:
pd.read_sql_query("""
SELECT
    SUM(
        CASE
            WHEN status = 'Delivered' THEN 1
            ELSE 0
        END
    ) AS delivered_orders,

    SUM(
        CASE
            WHEN status <> 'Delivered' THEN 1
            ELSE 0
        END
    ) AS not_delivered_orders

FROM orders
""", conn)

   delivered_orders  not_delivered_orders
0                 7                     4

CASE statements are used inside aggregate functions.

Delivered orders are counted separately from all other statuses
(Shipped, Pending, Cancelled).

## Q26. ACID Properties

### A - Atomicity
A transaction is treated as a single unit.
Either all operations succeed or all fail.

Example:
If ₹1000 is transferred from Account A to Account B,
both debit and credit must happen together.
If one fails, everything is rolled back.

---

### C - Consistency
A transaction must take the database from one valid state to another valid state.

Example:
If total money in the banking system is ₹10,000 before transfer,
it should remain ₹10,000 after transfer.

---

### I - Isolation
Multiple transactions should not interfere with each other.

Example:
Two users transferring money simultaneously should not see
incomplete changes made by the other transaction.

---

### D - Durability
Once a transaction is committed, the changes are permanently saved.

Example:
After a successful bank transfer, the updated balances remain
even if the database server crashes immediately afterward.

---

### Real-World Example: Bank Transfer

1. Debit ₹1000 from Account A.
2. Credit ₹1000 to Account B.
3. Commit transaction.

Atomicity:
Both operations happen together.

Consistency:
Total money remains unchanged.

Isolation:
Other users cannot see partial updates.

Durability:
After commit, the transfer remains permanent.

## Q27. Transaction Example Using BEGIN, COMMIT and ROLLBACK

In [41]:
transaction_sql = """
BEGIN TRANSACTION;

INSERT INTO orders
VALUES
(
    1011,
    102,
    '2024-09-01',
    'Pending',
    1598.00
);

INSERT INTO order_items
VALUES
(
    5016,
    1011,
    202,
    1,
    799.00,
    0
);

INSERT INTO order_items
VALUES
(
    5017,
    1011,
    208,
    1,
    799.00,
    0
);

UPDATE products
SET stock_qty = stock_qty - 1
WHERE product_id = 202;

UPDATE products
SET stock_qty = stock_qty - 1
WHERE product_id = 208;

COMMIT;
"""

In [42]:
try:
    conn.execute("BEGIN TRANSACTION")

    conn.execute("""
    INSERT INTO orders
    VALUES
    (1011,102,'2024-09-01','Pending',1598.00)
    """)

    conn.execute("""
    INSERT INTO order_items
    VALUES
    (5016,1011,202,1,799.00,0)
    """)

    conn.execute("""
    INSERT INTO order_items
    VALUES
    (5017,1011,208,1,799.00,0)
    """)

    conn.execute("""
    UPDATE products
    SET stock_qty = stock_qty - 1
    WHERE product_id = 202
    """)

    conn.execute("""
    UPDATE products
    SET stock_qty = stock_qty - 1
    WHERE product_id = 208
    """)

    conn.commit()

    print("Transaction committed successfully")

except Exception as e:
    conn.rollback()
    print("Transaction rolled back")
    print(e)

Transaction committed successfully

Transaction Flow:

1. Insert a new order.
2. Insert two order items.
3. Reduce stock quantity.
4. If every step succeeds → COMMIT.
5. If any step fails → ROLLBACK.

This ensures Atomicity and Consistency.